"""add_tracked_novels

Revision ID: 0a68de38c35d
Revises: 4d43af0bd879
Create Date: 2026-03-07 22:22:28.733220
"""

from typing import Sequence, Union

import sqlmodel
import sqlmodel as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a68de38c35d"
down_revision: Union[str, Sequence[str], None] = "4d43af0bd879"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

try:
    dialect = op.get_context().dialect.name
except Exception:
    dialect = ""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracked_novels",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("novel_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("novel_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_known_chapters", sa.Integer(), nullable=False),
        sa.Column("last_checked_at", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("check_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("auto_download", sa.Boolean(), nullable=False),
        sa.Column("output_format", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "novel_url", name="uq_tracked_user_novel"),
    )
    op.create_index("ix_tracked_novels_active", "tracked_novels", ["is_active", "last_checked_at"], unique=False)
    op.create_index(op.f("ix_tracked_novels_created_at"), "tracked_novels", ["created_at"], unique=False)
    op.create_index(op.f("ix_tracked_novels_is_active"), "tracked_novels", ["is_active"], unique=False)
    op.create_index(op.f("ix_tracked_novels_novel_id"), "tracked_novels", ["novel_id"], unique=False)
    op.create_index(op.f("ix_tracked_novels_novel_url"), "tracked_novels", ["novel_url"], unique=False)
    op.create_index(op.f("ix_tracked_novels_updated_at"), "tracked_novels", ["updated_at"], unique=False)
    op.create_index(op.f("ix_tracked_novels_user_id"), "tracked_novels", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracked_novels_user_id"), table_name="tracked_novels")
    op.drop_index(op.f("ix_tracked_novels_updated_at"), table_name="tracked_novels")
    op.drop_index(op.f("ix_tracked_novels_novel_url"), table_name="tracked_novels")
    op.drop_index(op.f("ix_tracked_novels_novel_id"), table_name="tracked_novels")
    op.drop_index(op.f("ix_tracked_novels_is_active"), table_name="tracked_novels")
    op.drop_index(op.f("ix_tracked_novels_created_at"), table_name="tracked_novels")
    op.drop_index("ix_tracked_novels_active", table_name="tracked_novels")
    op.drop_table("tracked_novels")
    # ### end Alembic commands ###
